### ISSUE TITLE
Icon and theme design

### ISSUE THREAD

**Issue by rugk** [rugk/unicodify#3]
@tdulcet let’s do some brainstorming.

Do you have any ideas?

**Comment by tdulcet** [comment]
Unfortunately, I do not have any ideas. I liked that you used an emoji as the icon for the Awesome Emoji Picker and think it would be cool to also do that for this. However, I looked through [the emojis](https://unicode.org/emoji/charts/full-emoji-list.html) and did not see anything that was relevant...  As you know, there are no existing add-ons that can do Unicode autocorrection or change the Unicode font and just two that can change the case (see [here](https://addons.mozilla.org/en-US/firefox/addon/titlecase/) and [here](https://addons.mozilla.org/en-US/firefox/addon/change-case/)), so there is not much we can really get inspiration from. You probably noticed that I used the `🗛` symbol [as a placeholder](https://github.com/rugk/awesome-emoji-picker/pull/93/files#diff-594c44a28df5453d166af1cfc08191e04d1a2576a04161c773b2ea80e2dac86cR178).

**Comment by dvergeylen** [comment]
A unicode symbol would be cool.

Some ideas:
```verbatim
∐ ∴ ≈ ⌗ ⌘ ⌨ ☊ ⦿ ⇌
```

**Comment by rugk** [comment]
Hmm yeah, but maybe an Unicode symbol this add-on actually uses?

Also, I could imagine doing something with an `U` (from the add-on name), maybe a similar looking character or a combination of an U or so…

**Comment by dvergeylen** [comment]
>Also, I could imagine doing something with an U (from the add-on name), maybe a similar looking character or a combination of an U or so…

υ U+03C5 (unicode greek small letter upsilon)?
Github's font doesn't render it correctly (at least on Linux) but other fonts well:

![Screenshot_2020-12-04 unicode υ at DuckDuckGo](https://user-images.githubusercontent.com/8804879/101136247-58f72a00-360d-11eb-906b-deddbc15185f.png)

**Comment by rugk** [comment]
Awesome! Thanks. Indeed that looks quite nice, I'll play around with that.

**Comment by rugk** [comment]
I'm trying something with interpolate in Knscape and it… fails miserably… :laughing: 
![](https://gitlab.com/inkscape/inbox/uploads/43f3a53fcfc71ed16d6633ebe6619754/image.png)
https://gitlab.com/inkscape/inbox/-/issues/3717#note_460893793

**Comment by rugk** [comment]
I'm thinking of some "layering", shawdoy-thing:
![grafik](https://user-images.githubusercontent.com/11966684/101207225-9c36b480-3670-11eb-9b65-c8dc9a1c7fb2.png)

That would represent what this add-on does, i.e. **change*/transform/resharp whatever…

Single-color looks surprisingly good though, but that alone is boring:
![grafik](https://user-images.githubusercontent.com/11966684/101207259-a953a380-3670-11eb-8aac-b201f1f3f9eb.png)

**Comment by rugk** [comment]
New idea, playing around with that:
![grafik](https://user-images.githubusercontent.com/11966684/101207572-19622980-3671-11eb-93fd-f8e0bb375acd.png)

**Comment by rugk** [comment]
Hmm, I've got something:
![grafik](https://user-images.githubusercontent.com/11966684/101212459-0c493880-3679-11eb-95a3-8c548f194a4f.png)


Only when you look twice, you see that the layering has a twist: You cannot quite follow the (black) background and it makes no sense as it is sometimes in the foreground and sometimes it is not.
It's somewhat inspired by [a Möbius strip](https://en.wikipedia.org/wiki/M%C3%B6bius_strip) or all these [crazy stairs](https://en.wikipedia.org/wiki/Penrose_stairs).

I've also tried making this more confusing, but currently I do not like that much:
![grafik](https://user-images.githubusercontent.com/11966684/101212578-3ef33100-3679-11eb-965b-c9ba622280b3.png)

The colors are still up-to-change. Currently it uses `#7d004f` (Meganta 80) and `#ff9400` (Orange 50). And black of course.
I try to stick to the Firefox Photon colors: https://design.firefox.com/photon/visuals/color.html

For example I now consider the magenta too dark when switching screens.
Maybe orange or teal 60 (`#00c8d7`)?
![grafik](https://user-images.githubusercontent.com/11966684/101212810-a8733f80-3679-11eb-8837-52bf8012ea63.png)

Also had a look if we only use the same color for the light parts to increase the already mentioned confusion aspect, and yeah it works (especially with the connector version now), but uhm, maybe too simple?  

![grafik](https://user-images.githubusercontent.com/11966684/101212977-f4be7f80-3679-11eb-8136-4bcbc0b828ba.png)

**Comment by rugk** [comment]
I've uploaded this draft in https://github.com/rugk/unicodify/pull/15/commits/4d403d96170dff0e3b6a8e1f86279bd75ef9e320 if you want to have a look or play around. (Try changing/enabling/disabling the layers) :smiley:

**Comment by tdulcet** [comment]
> I've uploaded this draft in https://github.com/rugk/unicodify/commit/4d403d96170dff0e3b6a8e1f86279bd75ef9e320 if you want to have a look or play around.

@rugk Wow, thanks for doing all this work! The official Unicode logo uses a purplish blue (`#5555FF`):
<img src="https://upload.wikimedia.org/wikipedia/commons/0/09/New_Unicode_logo.svg" width="300">

> The colors are still up-to-change.

I also like that the style guide says "Firefox Purple is commonly used to indicate privacy", since privacy is one of the [main benefits of this add-on](https://github.com/rugk/awesome-emoji-picker/pull/93#issuecomment-710780555). Here is a version that uses Teal 70 (`#008ea4`) and Purple 40 (`#ad3bff`): 
![image](https://user-images.githubusercontent.com/15305150/101238295-22182700-3694-11eb-977f-6c351c320348.png)

**Comment by rugk** [comment]
Ok so maybe we go with purple + Unicode blue (I think using the Unicode color here is okay, even though it's not in the Firefox styleguide, it looks similar and also happy).

**Comment by rugk** [comment]
Okay the problem with my idea here is that it has a low contrast, actually:
Both colors are quite dark.

![grafik](https://user-images.githubusercontent.com/11966684/113673105-d82e6480-96b8-11eb-87b4-6d37a86f98bc.png)

Lightening up the purple/now pink part `#e941ffff` solves this somewhat:
![grafik](https://user-images.githubusercontent.com/11966684/113673231-0449e580-96b9-11eb-9089-248713fe667a.png)

But if we'd go with teal-60 (`#00c8d7ff`) again, we get a brighter picture in general:
![grafik](https://user-images.githubusercontent.com/11966684/113673315-1fb4f080-96b9-11eb-94e6-2b3d97ffc12e.png)


Using the official magenat-50 `##ff1ad9` would make it stronger/brighter even more:

![grafik](https://user-images.githubusercontent.com/11966684/113673547-6c98c700-96b9-11eb-96cb-55afa63240c1.png)

Purple alone is unfortunately not so bright and looks rather dark with the big black text in front of that.

**Comment by rugk** [comment]
…except if we'd make a multi-color version, but I don't really like that and would not go that route as it complicates the image:

![grafik](https://user-images.githubusercontent.com/11966684/113673950-e7fa7880-96b9-11eb-9305-9d1011217427.png)

**Comment by tdulcet** [comment]
> Using the official magenat-50 `##ff1ad9` would make it stronger/brighter even more:
> 
> ![grafik](https://user-images.githubusercontent.com/11966684/113673547-6c98c700-96b9-11eb-96cb-55afa63240c1.png)

This version looks good and would be fine with me. Thanks again for doing all this work!

**Comment by rugk** [comment]
BTW in dark mode the icon looks great, actually! The pink looks as if it is some LED stripe in the night taken with a camera using time exposure.

![image](https://user-images.githubusercontent.com/11966684/129265704-0ade6150-76b2-4ae4-a4d3-0787a0919744.png)

**Comment by rugk** [comment]
Okay that could also be related to the fact that Firefox 90.0.2 on Fedora 34 here does not seem to properly show the pink stuff uff…:

![image](https://user-images.githubusercontent.com/11966684/129265941-d3e8a263-e128-4c7e-8857-0d0153e36a00.png)

**Comment by rugk** [comment]
@tdulcet Can you reproduce it? Shall I open a new issue…?

**Comment by tdulcet** [comment]
> @tdulcet Can you reproduce it? Shall I open a new issue…?

Umm, I do not see that pink stuff at the bottom, but I am not 100% sure what you meant the logo to look like either. Are you able to reproduce it in Chrome/Chromium? If not, it is likely a WebRender issue (similar to https://github.com/rugk/offline-qr-code/issues/263) and you may need to submit a bug on BMO. Here is what I get. Firefox 90.0.2:
![image](https://user-images.githubusercontent.com/15305150/129322003-d55d4a06-20d6-4852-8e73-5a52b4cc54ee.png)

Firefox 93 Nightly:
![image](https://user-images.githubusercontent.com/15305150/129322098-60e4182a-7d00-4b87-a8bc-5baecd73e64f.png)

Thunderbird 91:
![image](https://user-images.githubusercontent.com/15305150/129322296-6e035006-f845-4ed2-9dcd-19f1a1dea15b.png)

I believe part of the issue is that the SVGs and PNGs are different. SVG (see [here](https://raw.githubusercontent.com/rugk/unicodify/main/assets/unicodify-icon.svg)):
![image](https://raw.githubusercontent.com/rugk/unicodify/main/assets/unicodify-icon.svg)

PNG (see [here](https://raw.githubusercontent.com/rugk/unicodify/main/assets/unicodify-icon_128.png)):
![image](https://raw.githubusercontent.com/rugk/unicodify/main/assets/unicodify-icon_128.png)

I think you wanted it to look like the PNG version, so the SVGs are also broken. 😕

**Comment by rugk** [comment]
I guess I/Inscape uses, because the PNGs are obviously exported from Inkscape. I open a new issue.
